# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '.*.log'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    #    -   id: check-added-large-files
    -   id: double-quote-string-fixer
    -   id: forbid-submodules
    -   id: check-merge-conflict
    -   id: check-ast

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic, types-PyYAML, types-requests, types-paramiko, types-tabulate]

-   repo: https://github.com/myint/autoflake
    rev: 'v2.3.1'
    hooks:
    - id: autoflake
      args: [
        --in-place,
        --remove-unused-variables,
        --remove-all-unused-imports,
        --recursive
      ]

-   repo: https://github.com/pycqa/flake8
    rev: '7.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: [
          --max-line-length=110,
        ]

-   repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.1'
    hooks:
    - id: autopep8
      args: [
        --in-place,
        --aggressive,
        --aggressive,
        --max-line-length=110,
        --recursive
      ]

      # PROBLEMS WITH IMPORTS IN PYLINT!!!
      #-   repo: https://github.com/PyCQA/prospector
      #    rev: 1.10.0 # The version of Prospector to use, if not 'master' for latest
      #    hooks:
      #    -   id: prospector

      # -   repo: https://github.com/PyCQA/pylint
      #     rev: ''
      #     hooks:
      #     -   id: pylint
