# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '.*.log'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    #    -   id: check-added-large-files
    -   id: double-quote-string-fixer
    -   id: forbid-submodules
    -   id: check-merge-conflict
    -   id: check-ast

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic, types-PyYAML, types-requests, types-paramiko, types-tabulate]

-   repo: https://github.com/pycqa/flake8
    rev: '7.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8

-   repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.1'
    hooks:
    - id: autopep8
      args: [--max-line-length=110, --diff]

-   repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.12
    hooks:
      - id: uv-lock
      # PROBLEMS WITH IMPORTS IN PYLINT!!!
      #-   repo: https://github.com/PyCQA/prospector
      #    rev: 1.10.0 # The version of Prospector to use, if not 'master' for latest
      #    hooks:
      #    -   id: prospector

      # -   repo: https://github.com/PyCQA/pylint
      #     rev: ''
      #     hooks:
      #     -   id: pylint
